-- ===== role -> permission mapping =====
INSERT INTO role_permissions (role_code, permission_code) VALUES
  -- ADMIN: all
  ('ADMIN', 'PASSWORD_CHANGE'),
  ('ADMIN', 'USER_CREATE'),
  ('ADMIN', 'USER_ENABLE_DISABLE'),
  ('ADMIN', 'USER_ROLE_CHANGE'),
  ('ADMIN', 'MODEL_RELOAD'),
  ('ADMIN', 'MODEL_UPLOAD'),
  ('ADMIN', 'MODEL_TRAIN'),
  ('ADMIN', 'NEWS_CATEGORY_CREATE'),
  ('ADMIN', 'NEWS_ARTICLE_CREATE'),
  ('ADMIN', 'NEWS_CATEGORY_DISABLE'),
  ('ADMIN', 'NEWS_ARTICLE_DISABLE'),
  ('ADMIN', 'NEWS_HASHTAG_MASTER'),
  ('ADMIN', 'NEWS_ARTICLE_HASHTAG_EDIT'),

  -- USER_MGR
  ('USER_MGR', 'PASSWORD_CHANGE'),
  ('USER_MGR', 'USER_CREATE'),
  ('USER_MGR', 'USER_ENABLE_DISABLE'),
  ('USER_MGR', 'USER_ROLE_CHANGE'),

  -- MODEL_MGR
  ('MODEL_MGR', 'PASSWORD_CHANGE'),
  ('MODEL_MGR', 'MODEL_RELOAD'),
  ('MODEL_MGR', 'MODEL_UPLOAD'),
  ('MODEL_MGR', 'MODEL_TRAIN'),

  -- DEMO（PASSWORD_CHANGE は付与しない）
  ('DEMO', 'MODEL_RELOAD'),
  ('DEMO', 'MODEL_UPLOAD'),
  ('DEMO', 'MODEL_TRAIN'),

  -- NEWS_CREATOR
  ('NEWS_MGR', 'PASSWORD_CHANGE'),
  ('NEWS_MGR', 'NEWS_CATEGORY_CREATE'),
  ('NEWS_MGR', 'NEWS_ARTICLE_CREATE'),
  ('NEWS_MGR', 'NEWS_CATEGORY_DISABLE'),
  ('NEWS_MGR', 'NEWS_ARTICLE_DISABLE'),
  ('NEWS_MGR', 'NEWS_HASHTAG_MASTER'),
  ('NEWS_MGR', 'NEWS_ARTICLE_HASHTAG_EDIT'),

  -- USER
  ('USER', 'PASSWORD_CHANGE')
ON CONFLICT (role_code, permission_code) DO NOTHING;
